name: ALLSurvival
main: ALLSurvival\ALLSurvival
version: 1.3.1
author: Zzm
api: [1.0.0]
load: STARTUP
description: LockCreative....
commands:
 ac:
  permission: ALLSurvival.ac
  description: Allow a persion to use creative
  usage: /ac <player>
 dc:
  permission: ALLSurvival.dc
  description: Disllow a persion to use creative
  usage: /dc <player>
 clist:
  permission: ALLSurvival.clist
  description: see the clist
  usage: /clist
 add:
  permission: ALLSurvival.add
  description: Allow a persion to use all the commands of AllSurvival
  usage: /add <player>

permissions:
 ALLSurvival:
  default: op
  description: allow all ALLSurvival
  children:
     ALLSurvival.ac:
      default: op
      description: Allow a persion to use creative
     ALLSurvival.dc:
      default: op 
      description: Disllow a persion to use creative
     ALLSurvival.clist:
      default: op 
      description: see the clist
     ALLSurvival.add:
      default: op 
      description: Allow a persion to use all the commands of AllSurvival
